site_name: Micromouse Docs
docs_dir: site

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands:
      - Movement: commands/movement.md
      - Loop : commands/loop.md
      - Repeat: commands/repeat.md
      - Break: commands/break.md

theme:
  name: material
