site_name: Micromouse Docs
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
      - Movement: reference/movement.md
      - Variables: reference/variables.md
      - Control Flow: reference/controlflow.md

theme:
  name: material
